# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1308f881d33c9fe995a0681f8d8e48345f0c26161cdc97f10d5de5726e88fdc022de0bffb6afa7a2f46e3696fee24d42b534142b7c69bab91d45478c677711f2

test:
  secret_key_base: a57ba99280ec0a2c213e77457583ba97c5745a3ec9bf29c8b2f2550ff5f16f11629cb1c9fd219b80a0f91c80d2653829ef4f4bd7a853d3fdc07798bb10bba514

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
